### PR TITLE
Increase build image backoff time and attempts

### PR DESCRIPTION
**Pull request by jdisanti**
## Motivation and Context
Experimenting with increasing backoff to reduce total failures due to throttling.

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by jdisanti** [comment]
Hmmm... Changing the acquire script causes the image to be sourced from the artifacts, so I can't actually tell if this PR improved the situation 🤔

**Review by ysaito1001 — APPROVED** [review]
Can & should we make these values configurable though command line arguments or environment variables?

**Comment by jdisanti** [comment]
Unfortunately, I don't have any evidence that this improves things since changing the acquire script resulted in rebuilding the image. Evidence can be achieved once https://github.com/awslabs/smithy-rs/pull/2269 is merged, although this PR may not even be needed after https://github.com/awslabs/smithy-rs/pull/2265. If someone is annoyed enough, they can go ahead and merge this to see if it improves the situation before those other PRs are merged.

> Can & should we make these values configurable through command line arguments or environment variables?

We certainly could. Maybe next round.

**Comment by jdisanti** [comment]
Found evidence of this working in the logs:
```
Base image not found locally.
Attempting to pull remote image public.ecr.aws/w0m4q9l7/github-awslabs-smithy-rs-ci:500f09323f082da417966b8933087e93249e2715 (attempt 1)...
Docker pull output:
-------------------

-------------------
Error response from daemon: toomanyrequests: Rate exceeded
-------------------
Docker pull failed due to throttling. Waiting and trying again...
Attempting to pull remote image public.ecr.aws/w0m4q9l7/github-awslabs-smithy-rs-ci:500f09323f082da417966b8933087e93249e2715 (attempt 2)...
Docker pull output:
-------------------
500f09323f082da417966b8933087e93249e2715: Pulling from w0m4q9l7/github-awslabs-smithy-rs-ci
```

**Pull request merged**
