### PR TITLE
Rfc30/various fixes

### PR DESCRIPTION
**Pull request by thomas-k-cameron**
## Motivation and Context
This PR implements RFC30.

## Description
- Tests against features behind unstable gates
- Adds serde(skip) to `@streaming bytes` field
- Imports serde on files where `serde(skip)` is used.
- Implements serde traits to ErrorMetadata
- Fixes name of the feature-gate to serde-{serialize/deserialize} from serialize/deserialize on aws_smithy_types

## Checklist
NA

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by thomas-k-cameron** [comment]
It seems like there are some issues with the server side python binding.

I'm not quite sure where it's coming from since I never touched the server side code.

@Velfi 
Any idea?

**Comment by Velfi** [comment]
> It seems like there are some issues with the server side python binding.
> 
> I'm not quite sure where it's coming from since I never touched the server side code.
> 
> @Velfi Any idea?

I'm not sure, but I'd assume it has to do with a bad merge/messed up git history. I won't have time to dig in any time soon. You'd likely get farther, faster moving your work into your fork so that you aren't dependent on us for merges. We (as a team) don't currently have the time to give such large PRs the appropriate review.

**Comment by thomas-k-cameron** [comment]
Gotcha.

Changes my PR has mostly comes from the main branch. (I wanted to reflect the latest changes.)

Let me figure out a way to make things smaller.

**Comment by thomas-k-cameron** [comment]
@velfi

If you merge them directly to `main` branch, you wouldn't need to go through the trouble of updating the `unstable` branch.

I will try and re-organize my PRs.

Does it work?

**Comment by thomas-k-cameron** [comment]
Closed in favour of https://github.com/awslabs/smithy-rs/pull/2615

**Pull request closed without merging**
