### PR TITLE
Improve instructions to update changelogs

### PR DESCRIPTION
**Pull request by david-perez**
The name of the subcommand has an extra `s`. I also struggled to find
the referenced tool.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by crisidev — APPROVED** [review]

**Comment by rcoh** [comment]
actually, should it say `Update CHANGELOG.next.toml`?

**Comment by david-perez** [comment]
> actually, should it say Update CHANGELOG.next.toml?

Yeah, let's make the instructions clearer: first update `CHANGELOG.next.toml`, then run the CLI tool.

**Comment by rcoh** [comment]
(the CLI tools is only run when cutting a release, just to clarify)

**Review by crisidev — APPROVED** [review]

**Comment by david-perez** [comment]
Closing because of staleness.

**Pull request closed without merging**
