### PR TITLE
RustType renders types with wrong syntax

### PR DESCRIPTION
**Pull request by 82marbag**
The correct syntax is `HashMap::<T, U>` instead of `HashMap<T, U>` and so on.

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by Velfi** [comment]
Both work: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1f530b9045d325bc05d925c7fb0fdda3

Did this formatting cause a specific problem for you?

**Comment by 82marbag** [comment]
> Both work: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1f530b9045d325bc05d925c7fb0fdda3
> 
> Did this formatting cause a specific problem for you?

Ok, I used the one in the Rust docs. Anyway, it doesn't work for maps: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d9cfd082eeb016be7ce251a526527a40

**Comment by 82marbag** [comment]
> Both work: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1f530b9045d325bc05d925c7fb0fdda3
> 
> Did this formatting cause a specific problem for you?

For example: [this test](https://github.com/awslabs/smithy-rs/blob/40f466213b038916f37528c1b51cc75cea11b02a/codegen-core/src/test/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustTypeTest.kt#L77) is not [valid Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a2d8614350f8430a0a59d30e8625d19c)

**Comment by Velfi** [comment]
Fair enough. I think previously we were only using this in the 'type assertion' position and that's why we never ran into the issue. Given that your version works in both places, you get my ✅.

**Review by Velfi — APPROVED** [review]

**Review by david-perez — APPROVED** [review]

**Pull request merged**
