### PR TITLE
Moved RDS code examples into rds directory

### PR DESCRIPTION
**Pull request by Doug-AWS**
*Issue #, if available:*
RDS code examples were in separate directories.

*Description of changes:*
Moved .RS files into rds/src/bin.
Part of resolving issue #400.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rcoh** [comment]
Since RDS and RDS-data are separate services I wonder if they should be in separate directories. Thoughts?

**Comment by Doug-AWS** [comment]
I'll split them up into separate directories.

**Comment by Doug-AWS** [comment]
Done

**Review by rcoh — APPROVED** [review]
LGTM, you will need to delete the old directory for CI to pass

**Pull request merged**
