### PR TITLE
Enable the invoke_model_with_response_stream API

### PR DESCRIPTION
**Pull request by rcoh**
This API is a streaming API—I tested it manually, an E2E test an example are forthcoming. I also removed the unused `config` service from the smoketest and added bedrock-runtime.

## Motivation and Context
This API is suppressed by default because it's an event stream API

## Testing
https://gist.github.com/rcoh/ce61429303a56fefd65ba05bd36d28fc works

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by jdisanti — COMMENTED** [review]
Why was `config.json` deleted?

**Comment by rcoh** [comment]
>  I also removed the unused config service from the smoketest and added bedrock-runtime.

**Review by Velfi — APPROVED** [review]

**Comment by jdisanti** [comment]
It's not unused. In fact, it's testing codegen for awsJson1_1: https://github.com/awslabs/smithy-rs/blob/main/aws/sdk/aws-models/README.md

**Review by jdisanti — APPROVED** [review]
Awesome! 🚀

**Review by ysaito1001 — APPROVED** [review]

**Pull request merged**
