### PR TITLE
Update with flexible zeroize version

### PR DESCRIPTION
**Pull request by ethyi**
## Motivation and Context
Updating the zeroize version in Cargo.toml in aws-types.
Specifying zeroize 1.4.1 only allows 1.4.1 and up. Many crates in production use 1.4 and less. Downgrading to 1.0.0 provides flexible versioning without sacrificing functionality.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jdisanti — APPROVED** [review]
I don't see any Rustsec advisories on the `zeroize` crate, and the `aws-config` crate is currently using `"1"`, so I think this change should be fine as long as CI passes.

**Comment by jdisanti** [comment]
If you want to be credited in the changelog with the next release, then be sure to add an `[[aws-sdk-rust]]` entry to [`CHANGELOG.next.toml`](https://github.com/awslabs/smithy-rs/blob/main/CHANGELOG.next.toml).

**Comment by jdisanti** [comment]
It looks like the following message from the PR template's description was omitted when creating the PR:

> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Unfortunately, I can't merge this until it is added back in. But otherwise, it all looks good!

**Comment by ethyi** [comment]
### Motivation and Context

Updating the zeroize version in Cargo.toml in aws-types.
Specifying zeroize 1.4.1 only allows 1.4.1 and up. Many crates in production use 1.4 and less. Downgrading to 1.0.0 provides flexible versioning without sacrificing functionality.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Comment by jdisanti** [comment]
Thank you for the contribution! I'll work on getting this merged.

**Pull request merged**
