### PR TITLE
Do not generate the operation registry when there are no operations

### PR DESCRIPTION
**Pull request by david-perez**
Do not generate the operation registry, nor the operation handler
traits, when there are no operations in the service closure.

## Testing

Without this commit, we codegen a crate for the `empty.smithy` service that
cannot be compiled.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by crisidev — APPROVED** [review]

**Comment by david-perez** [comment]
There's no harm in adding the test to the client too I guess.

**Review by rcoh — APPROVED** [review]
LGTM

**Review by rcoh — COMMENTED** [review]
let's make this fail

**Comment by david-perez** [comment]
I'll work on making it throw an exception instead of logging a warning.

**Comment by LukeMathWalker** [comment]
I assume we can close this since the registry is gone? @david-perez

**Pull request closed without merging**
