### PR TITLE
Debug mode

### PR DESCRIPTION
**Pull request by rcoh**
## Motivation and Context
It can be hard to figure out where generated code comes from. This adds support for `debugMode` in smithy-build.json.

## Description
1. Update to use non-deprecated versions of codegen writer
2. Add support for `debugMode`:

image

## Testing
- ran codegen with it turned on and off and verified expected results

## Checklist

- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jdisanti** [comment]
Changes look good, but it fails to compile in CI:
```
e: smithy-rs/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/ServerCodegenVisitor.kt: (91, 89): No value passed for parameter 'codegenConfig'
e: smithy-rs/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/ServerRustSettings.kt: (45, 21): Type mismatch: inferred type is Set<???> but Boolean was expected
```

**Review by jdisanti — APPROVED** [review]
Awesome!

**Review by david-perez — APPROVED** [review]
Love it.

I would like this feature to be prominently documented in some README, since this is an extremely useful feature for new contributors but will rarely be used by experienced ones.

**Comment by crisidev** [comment]
This is amazing Russell!

**Review by crisidev — APPROVED** [review]

**Pull request merged**
