### PR TITLE
Run lints against changed VCS files once

### PR DESCRIPTION
**Pull request by david-perez**
We're currently running the lints against changed files twice, causing
some output lines to be duplicated.

Switch to `git ls-files`, which can list files in the index and the
working (staged and unstaged), as well as unignored untracked files.

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by LukeMathWalker — APPROVED** [review]

**Review by jdisanti — APPROVED** [review]

**Review by rcoh — CHANGES_REQUESTED** [review]
this misses files that are in the current diff. We should combine them in a set, but `git ls-tree -r HEAD --name-only` does not include files that are staged for commit.

```
➜  rfcs git:(4d51d6659) ✗ git ls-tree -r --name-only HEAD | grep rfc0027
➜  rfcs git:(4d51d6659) ✗ git diff --name-only | grep rfc0027           
design/src/rfcs/rfc0027_endpoints_20.md
```

**Comment by jdisanti** [comment]
Is there a reason we don't just use the file list that `pre-commit` gives as arguments?

**Comment by david-perez** [comment]
I'm sorry I don't understand how you were able to get that output. Can you share the sequence of commands?

> but git ls-tree -r HEAD --name-only does not include files that are staged for commit.

`git diff` doesn't either, right? It diffs tracked files against the _working directory_.

```console
➜  SmithyRsSource git:(main) git checkout -B main upstream/main
branch 'main' set up to track 'upstream/main'.
Reset branch 'main'
Your branch is up to date with 'upstream/main'.
➜  SmithyRsSource git:(main) echo "foo" > design/src/rfcs/rfc0027.md
➜  SmithyRsSource git:(main) ✗ git ls-tree -r --name-only HEAD | grep rfc0027
➜  SmithyRsSource git:(main) ✗ git diff --name-only | grep rfc0027
➜  SmithyRsSource git:(main) ✗
```

Only `git diff --staged` diffs against the staging directory.

```console
➜  SmithyRsSource git:(main) ✗ git add design/src/rfcs/rfc0027.md
➜  SmithyRsSource git:(main) ✗ git ls-tree -r --name-only HEAD | grep rfc0027
➜  SmithyRsSource git:(main) ✗ git diff --staged --name-only | grep rfc0027
design/src/rfcs/rfc0027.md
```

After the file is committed, `git diff` will now report changes in the working tree against the committed tree:

```console
➜  SmithyRsSource git:(main) ✗ git commit -m "Add rfc"
[main d89e67af1] Add rfc
 1 file changed, 1 insertion(+)
 create mode 100644 design/src/rfcs/rfc0027.md
➜  SmithyRsSource git:(main) echo "bar" > design/src/rfcs/rfc0027.md
➜  SmithyRsSource git:(main) ✗ git diff --name-only | grep rfc0027
design/src/rfcs/rfc0027.md
```

But since the file is tracked, `git ls-tree` will also report it:

```console
➜  SmithyRsSource git:(main) ✗ git ls-tree -r --name-only HEAD | grep rfc0027
design/src/rfcs/rfc0027.md
```

**Comment by david-perez** [comment]
@rcoh provided the counterexample of unstaged changes in a staged file.

```console
➜  smithy-rs git:(main) ✗ touch my-new-file
➜  smithy-rs git:(main) ✗ git add my-new-file
➜  smithy-rs git:(main) ✗ echo "some text" > my-new-file
➜  smithy-rs git:(main) ✗ git status
On branch main
Your branch is behind 'origin/main' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   my-new-file

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   my-new-file

➜  smithy-rs git:(main) ✗ git diff --name-only | grep my-new-file
my-new-file
➜  smithy-rs git:(main) ✗ git ls-tree -r --name-only HEAD | grep my-new-file
```

So `git ls-tree` is not sufficient.

I've learnt about `git ls-files`, which can essentially be used to combine `git diff`, `git diff --staged` and `git ls-tree` with the help of some flags.

This PR went stale; I've rewritten the branch's history to be a single commit using `git ls-files` and amended the PR's description.

**Review by rcoh — APPROVED** [review]
LGTM—if practical a short test might be good but I imagine it might be kind of annoying to set up the scaffolding

**Pull request merged**
