### PR TITLE
Move `SmithyHttpServer` to `ServerCargoDependency.kt`

### PR DESCRIPTION
**Pull request by david-perez**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by crisidev — APPROVED** [review]

**Comment by crisidev** [comment]
How do I revoke approval? https://github.com/awslabs/smithy-rs/runs/5511154238?check_suite_focus=true#step:7:418

**Comment by rcoh** [comment]
is this good to go?

**Review by crisidev — APPROVED** [review]

**Comment by david-perez** [comment]
@rcoh Yes, but we need approval from someone from @awslabs/rust-sdk-owners :)

**Review by rcoh — APPROVED** [review]
🤦🏻 lgtm!

**Pull request merged**
