### PR TITLE
Update the smithy client's `call` and `call_raw` bounds

### PR DESCRIPTION
**Pull request by Velfi**
## Motivation and Context

#2324 
This PR enables changes needed to implement quota layers in the smithy client service builder

## Description

- **add:** `ParseHttpResponse` bound to smithy client's `call`/`call_raw`
- **add:** 'static to smithy client's `call`/`call_raw` `T`, `Retry`, and `R::Policy` bounds
- **remove:** Clone bound from `call`/`call_raw`'s Service bound
- **remove:** 'static bound from `Client::check`'s `R::Policy` bound
- **update:** prefer fully qualified `std::error::Error` to `Error`
- **update:** smithy client doc comment that was giving IntelliJ trouble
- **update:** unify naming of generic type args related to smithy client

## Testing

ran existing tests

## Checklist

- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
Is this a refactoring or a breaking change? I honestly got a bit lost trying to follow how the bounds have been restructured.

**Comment by Velfi** [comment]
> Is this a refactoring or a breaking change? I honestly got a bit lost trying to follow how the bounds have been restructured.

It's both, sorry. However, I don't expect it to actually break any users unless they were manually creating timeout futures to test something.

The core of this change is the updated `ParseHttpResponse` bound. Without that and the other changes, I was unable to add `MapRequestLayer`s into the service builder stack. I don't really understand why I needed to do this; It was just what worked.

**Comment by Velfi** [comment]
Waiting on an internal discussion before merging this.

**Comment by Velfi** [comment]
Closing this since I'm no longer taking an approach that requires this.

**Pull request closed without merging**
