### PR TITLE
Move re-exports into `types` and re-export `AggregatedBytes`

### PR DESCRIPTION
**Pull request by jdisanti**
## Motivation and Context
This implements https://github.com/awslabs/smithy-rs/issues/944.

## Checklist
- [x] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [x] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jdisanti** [comment]
Opening this PR as a draft to gather feedback. This change will also require updating all the examples, which I want to hold off on until consolidation is complete.

Open questions: 
1. Should the re-exported `SdkError` type follow other re-exports and be in the `types` module, or should it remain in root?
2. Should we re-export types even if they're not used? For example, should `ByteStream` be re-exported by a service that has no streaming operations?

**Comment by Velfi** [comment]
> - Should the re-exported `SdkError` type follow other re-exports and be in the types module, or should it remain in root?

I like setting and sticking to conventions so putting it in types makes sense to me unless that somehow makes codegen more difficult.

> - Should we re-export types even if they're not used? For example, should `ByteStream` be re-exported by a service that has no streaming operations?

On first thought, I think it shouldn't be re-exported. However, I'm worried about SDKs that add and then remove a bytestream based api. Is that something we need to consider or will that never happen?

**Review by rcoh — APPROVED** [review]

**Comment by rcoh** [comment]
generally APIs can't be removed

**Comment by jdisanti** [comment]
Will proceed with:
1. All re-exports go into the `types` namespace
2. Don't re-export unused types

**Comment by jdisanti** [comment]
Examples fixed in https://github.com/awsdocs/aws-doc-sdk-examples/pull/2776

**Review by rcoh — APPROVED** [review]

**Pull request merged**
