### PR TITLE
aws-smithy-query: bump to urlencoding v2.1

### PR DESCRIPTION
**Pull request by benesch**
## Motivation and Context

urlencoding v2.1 is a SemVer-breaking change. We use `urlencoding` in our own crates downstream, and we want to have only one copy of `urlencoding`, so we need `aws-smithy-query` to upgrade to.

## Description

Bumps `aws-smithy-query` from urlencoding v1.3 to urlencoding v2.1.

## Testing

CI coverage should be enough!

## Checklist

- [x] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by benesch** [comment]
The test failures look like permissions errors that are unrelated to the contents of this PR!

**Comment by rcoh** [comment]
do you mind adding a changelog entry on the off chance it helps debug some future issue? LGTM otherwise, thanks for doing this!

**Review by rcoh — APPROVED** [review]
LGTM!

**Comment by benesch** [comment]
Happy to add the changelog, but don't want to overwrite your merge! Ok to just push up the new commit, or are you already on it?

**Comment by rcoh** [comment]
oh you can just pull it down—I just clicked the merge button on Github (or
feel free to overwrite)

**Comment by benesch** [comment]
Well, I added an entry for smithy-rs. Do I also need to add an entry for aws-sdk-rust? It's not clear to me whether "aws-smithy-query" counts as an AWS SDK runtime crate or not.

**Review by rcoh — APPROVED** [review]

**Pull request merged**
