### PR TITLE
Update pretty_assertions

### PR DESCRIPTION
**Pull request by Velfi**
## Motivation and Context

https://github.com/awslabs/aws-sdk-rust/pull/734

## Description

`pretty_assertions` v1.0 depends on an unmaintained crate. Upgrading to 1.3 will fix this.

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by jdisanti — APPROVED** [review]

**Review by ysaito1001 — APPROVED** [review]
Thank you!

**Comment by crisidev** [comment]
Any reason we don't use `1.3` everywhere? Some entries are `1.3.0`

**Comment by Velfi** [comment]
> Any reason we don't use `1.3` everywhere? Some entries are `1.3.0`

For some reason, I'm under the impression that libraries should use more general version numbers and that tools should use specific versions. I've done some introspection and I'm not sure where the impression comes from.

**Comment by jjant** [comment]
> For some reason, I'm under the impression that libraries should use more general version numbers and that tools should use specific versions. I've done some introspection and I'm not sure where the impression comes from.

I'm not sure what you mean, cargo treats both as equivalent.

**Comment by Velfi** [comment]
> I'm not sure what you mean, cargo treats both as equivalent.

Yeah, If I had any clarity I would have set the tool versions to `=1.3.0`. I'll make them all the same.

**Review by crisidev — APPROVED** [review]

**Pull request merged**
