### PR TITLE
Version bump smithy-rs

### PR DESCRIPTION
**Pull request by jdisanti**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by david-perez — APPROVED** [review]

**Comment by david-perez** [comment]
I don't understand why @awslabs/rust-sdk-owners is still required as an approver after https://github.com/awslabs/smithy-rs/pull/1618.

I'm going to try closing and reopening the PR.

**Comment by david-perez** [comment]
No luck. I've created https://github.com/david-perez/testing-codeowners to debug `CODEOWNERS` behavior. We can cut an issue to https://github.com/github/docs/issues if it turns out the documented semantics are incorrect.

**Comment by jdisanti** [comment]
We could create a third group that includes the members of both groups and assign that group to the `gradle.properties` file in `CODEOWNERS`.

**Comment by david-perez** [comment]
Oh never mind, it appears that it worked once CI finished. This is what I'm now seeing in my GitHub UI: it says `@awslabs/rust-sdk-owners` is a pending reviewer, but the "Squash and merge" button is now not greyed out.

image

**Pull request merged**
