### PR TITLE
Set server response headers

### LINKED ISSUE #1071: Assert against headers in server response protocol tests
In server response protocol tests, we're not asserting that the response contains the expected headers. We only assert body and HTTP status code.

Example ([link](https://github.com/awslabs/smithy/blob/14e6dce9f2d21075dcc0d827166eec63b692609e/smithy-aws-protocol-tests/model/restJson1/http-headers.smithy#L283-L283)):

```
{
    id: "RestJsonSupportsNaNFloatHeaderOutputs",
    documentation: "Supports handling NaN float header values.",
    protocol: restJson1,
    code: 200,
    headers: {
        "X-Float": "NaN",
        "X-Double": "NaN",
    },
    params: {
        headerFloat: "NaN",
        headerDouble: "NaN",
    }
}
```

Generates:

```rust
/// Supports handling NaN float header values.
/// Test ID: RestJsonSupportsNaNFloatHeaderOutputs
#[tokio::test]
#[should_panic]
async fn rest_json_supports_na_n_float_header_outputs_response() {
    let output = crate::output::InputAndOutputWithHeadersOutput::builder()
        .set_header_float(Some(
            <f32 as aws_smithy_types::primitive::Parse>::parse_smithy_primitive("NaN")
                .expect("invalid string for number"),
        ))
        .set_header_double(Some(
            <f64 as aws_smithy_types::primitive::Parse>::parse_smithy_primitive("NaN")
                .expect("invalid string for number"),
        ))
        .build();
    let output = super::InputAndOutputWithHeadersOperationOutputWrapper(output);
    use axum_core::response::IntoResponse;
    let http_response = output.into_response();
    assert_eq!(
        http::StatusCode::from_u16(200).expect("invalid expected HTTP status code"),
        http_response.status()
    );
    let request_extensions = http_response
        .extensions()
        .get::<aws_smithy_http_server::RequestExtensions>()
        .expect("extension `RequestExtensions` not found");
    assert_eq!(request_extensions.namespace, "aws.protocoltests.restjson");
    assert_eq!(
        request_extensions.operation_name,
        "InputAndOutputWithHeaders"
    );
}
```

### PR DESCRIPTION
**Pull request by david-perez**
This commit adds support for the `httpHeaders` and `httpPrefixHeaders`
when applied to error shapes and operation output shapes to the server
implementation.

The presence of response headers is now asserted against in server
protocol tests.

Functions that set headers in requests that were used by the client have
been refactored into `HttpBindingGenerator.kt`, since they are useful
for the server to set headers in responses.

This commit also makes error shapes be serialized in JSON responses with
a `__type` field in the body, in favor of setting the `X-Amzn-Errortype`
header, as recommended by the specs of all AWS protocols.

This commit also removes the generation of operation structs for the
server in `ProtocolGenerator.kt`, since they are not useful for the
server implementation.

Closes #1071 #1075.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by david-perez** [comment]
How do I fix the failing unit tests from `RequestBindingGeneratorTest.kt`?

I've moved setting headers to `http_serde.rs`, so now I'm generating this in `input.rs`:

```rust
#[allow(clippy::unnecessary_wraps)]fn update_http_builder(
                input: &crate::input::PutObjectInput,
                builder: http::request::Builder
            ) -> std::result::Result<http::request::Builder, aws_smithy_http::operation::BuildError> {
    let mut uri = String::new();
    uri_base(input, &mut uri)?;
    uri_query(input, &mut uri)?;
    let builder = crate::http_serde::add_headers_put_object(input, builder)?;
    Ok(builder.method("PUT").uri(uri))
}
```

whereas previously setting headers was done _inside_ `input.rs`.

The problem is when running the unit test, the writer is solely for `input.rs`; `http_serde.rs` never gets generated. Where do returned `RuntimeType`s eventually get flushed to the files where their module is hosted?

**Review by crisidev — APPROVED** [review]
Well done, very clear and comprehensive!

**Comment by guymguym** [comment]
Hey @david-perez Is this blocked on something?
I would be happy to rebase on it for the streaming body PR when possible.
Thanks

**Comment by david-perez** [comment]
> Hey @david-perez Is this blocked on something? I would be happy to rebase on it for the streaming body PR when possible. Thanks

There are failing unit tests in `RequestBindingGeneratorTest.kt` that I don't know how to fix, see my comment above https://github.com/awslabs/smithy-rs/pull/1086#issuecomment-1016643197. We'll try to take a look at how to fix them shortly.

But yes, you can start rebasing the streaming PR on top of this branch to continue working on it.

**Pull request merged**
