### PR TITLE
Update OperationInputTestDecorator to find operation shape by name 

### PR DESCRIPTION
**Pull request by mcmasn-amzn**
## Motivation and Context
Addresses https://github.com/awslabs/smithy-rs/issues/2767

This fixes an issue for users who write endpoint tests that rely on an operation and service shape from different namespaces.

## Description
Instead of assuming operation namespace matches service namespace, 

## Testing
`./gradlew :aws:sdk-codegen:test`

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by rcoh** [comment]
LGTM! did a quick audit to make sure this doesn't cause a performance regression—generation times for the SDK seem to be about the same.

**Comment by rcoh** [comment]
If you don't mind adding a quick entry with the bugfix to `CHANGELOG.next.toml` under the `[smithy-rs]` tag we'll get this merged

**Review by rcoh — COMMENTED** [review]
LGTM—pending changelog.

**Comment by mcmasn-amzn** [comment]
Thanks @rcoh. Just pushed a commit to add the changelog entry

**Review by rcoh — APPROVED** [review]

**Pull request merged**
